"""create initial learning schema

Revision ID: 2eb16903ecf0
Revises: 
Create Date: 2026-09-10 04:34:12.652406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb16903ecf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('form_level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topics_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_topic_subject_slug')
    )
    op.create_index(op.f('ix_topics_form_level'), 'topics', ['form_level'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_users_school_id_schools'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('form_level', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_classrooms_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_classrooms_teacher_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classrooms')),
    sa.UniqueConstraint('school_id', 'name', 'academic_year', name='uq_classroom_school_name_year')
    )
    op.create_index(op.f('ix_classrooms_school_id'), 'classrooms', ['school_id'], unique=False)
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('multiple_choice', 'true_false', 'short_answer', name='question_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_level'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_questions_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('assessment_type', sa.Enum('diagnostic', 'practice', 'post_learning', name='assessment_type'), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='assessment_status'), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_assessment_attempts_classroom_id_classrooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_assessment_attempts_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_assessment_attempts_topic_id_topics'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts'))
    )
    op.create_index(op.f('ix_assessment_attempts_assessment_type'), 'assessment_attempts', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_classroom_id'), 'assessment_attempts', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_status'), 'assessment_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_student_id'), 'assessment_attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_topic_id'), 'assessment_attempts', ['topic_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_enrollments_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_enrollments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('classroom_id', 'student_id', name='uq_enrollment_classroom_student')
    )
    op.create_index(op.f('ix_enrollments_classroom_id'), 'enrollments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('assessment_attempt_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('session_started', 'topic_selected', 'diagnostic_started', 'question_answered', 'tutor_interaction', 'practice_started', 'practice_completed', 'assessment_completed', 'session_completed', name='learning_event_type'), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], name=op.f('fk_learning_events_assessment_attempt_id_assessment_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_learning_events_classroom_id_classrooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_learning_events_question_id_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_learning_events_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_learning_events_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_events'))
    )
    op.create_index(op.f('ix_learning_events_assessment_attempt_id'), 'learning_events', ['assessment_attempt_id'], unique=False)
    op.create_index(op.f('ix_learning_events_classroom_id'), 'learning_events', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_occurred_at'), 'learning_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_learning_events_question_id'), 'learning_events', ['question_id'], unique=False)
    op.create_index(op.f('ix_learning_events_student_id'), 'learning_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_learning_events_topic_id'), 'learning_events', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_events_topic_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_student_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_question_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_occurred_at'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_classroom_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_assessment_attempt_id'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_classroom_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_assessment_attempts_topic_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_student_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_status'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_classroom_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_assessment_type'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_school_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_form_level'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
