"""add teaching assignments

Revision ID: 3784e43340f3
Revises: 0b4635f0af33
Create Date: 2026-09-19 18:57:07.543809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3784e43340f3'
down_revision: Union[str, Sequence[str], None] = '0b4635f0af33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_teaching_assignments_classroom_id_classrooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_teaching_assignments_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teaching_assignments_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teaching_assignments_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_assignments')),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'classroom_id', name='uq_teaching_assignment_teacher_subject_classroom')
    )
    op.create_index(op.f('ix_teaching_assignments_classroom_id'), 'teaching_assignments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_teaching_assignments_school_id'), 'teaching_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_teaching_assignments_subject_id'), 'teaching_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teaching_assignments_teacher_id'), 'teaching_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_assignments_teacher_id'), table_name='teaching_assignments')
    op.drop_index(op.f('ix_teaching_assignments_subject_id'), table_name='teaching_assignments')
    op.drop_index(op.f('ix_teaching_assignments_school_id'), table_name='teaching_assignments')
    op.drop_index(op.f('ix_teaching_assignments_classroom_id'), table_name='teaching_assignments')
    op.drop_table('teaching_assignments')
    # ### end Alembic commands ###
