"""add assessment answers

Revision ID: 93acd643dc91
Revises: 2eb16903ecf0
Create Date: 2026-09-10 19:26:09.987843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93acd643dc91'
down_revision: Union[str, Sequence[str], None] = '2eb16903ecf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('marks_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], name=op.f('fk_assessment_answers_assessment_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_assessment_answers_question_id_questions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_answers')),
    sa.UniqueConstraint('assessment_attempt_id', 'question_id', name='uq_assessment_answer_attempt_question')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_attempt_id'), 'assessment_answers', ['assessment_attempt_id'], unique=False)
    op.create_index(op.f('ix_assessment_answers_question_id'), 'assessment_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_answers_question_id'), table_name='assessment_answers')
    op.drop_index(op.f('ix_assessment_answers_assessment_attempt_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    # ### end Alembic commands ###
