"""add assessment questions

Revision ID: e9f58effb51f
Revises: eb77a0a5d211
Create Date: 2026-09-12 20:26:01.265509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f58effb51f'
down_revision: Union[str, Sequence[str], None] = 'eb77a0a5d211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], name=op.f('fk_assessment_questions_assessment_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_assessment_questions_question_id_questions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions')),
    sa.UniqueConstraint('assessment_attempt_id', 'position', name='uq_assessment_question_attempt_position'),
    sa.UniqueConstraint('assessment_attempt_id', 'question_id', name='uq_assessment_question_attempt_question')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_attempt_id'), 'assessment_questions', ['assessment_attempt_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_question_id'), 'assessment_questions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_questions_question_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_attempt_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    # ### end Alembic commands ###
