"""add tutor messages

Revision ID: eb77a0a5d211
Revises: 93acd643dc91
Create Date: 2026-09-12 19:03:04.513562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb77a0a5d211'
down_revision: Union[str, Sequence[str], None] = '93acd643dc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('assessment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], name=op.f('fk_tutor_messages_assessment_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], name=op.f('fk_tutor_messages_classroom_id_classrooms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_tutor_messages_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_tutor_messages_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_messages'))
    )
    op.create_index(op.f('ix_tutor_messages_assessment_attempt_id'), 'tutor_messages', ['assessment_attempt_id'], unique=False)
    op.create_index(op.f('ix_tutor_messages_classroom_id'), 'tutor_messages', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_tutor_messages_student_id'), 'tutor_messages', ['student_id'], unique=False)
    op.create_index(op.f('ix_tutor_messages_topic_id'), 'tutor_messages', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_messages_topic_id'), table_name='tutor_messages')
    op.drop_index(op.f('ix_tutor_messages_student_id'), table_name='tutor_messages')
    op.drop_index(op.f('ix_tutor_messages_classroom_id'), table_name='tutor_messages')
    op.drop_index(op.f('ix_tutor_messages_assessment_attempt_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    # ### end Alembic commands ###
